[project]
authors = ["Robert Massaioli <freecad@rmdir.app>"]
channels = ["freecad/label/dev", "conda-forge"]
description = "Advanced tools that work like Shapestrings but even more powerful."
name = "freecad.advanced_shapestrings"
platforms = ["osx-arm64", "linux-aarch64", "linux-64", "win-64", "osx-64"]
version = "0.1.0"

[pypi-dependencies]
freecad_advanced_shapestrings = { path = ".", editable = true }

[tasks]
test = "python tests/tests.py"

[dependencies]
freecad = ">=1.0.0,<2"